import Provider from '../context/Provider'
import './global.css'

export const metadata = {
	title: 'Welcome to apps/frontend',
	description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<Provider>
				<body className=''>{children}</body>
			</Provider>
		</html>
	)
}
